# Generated by Django 3.2.9 on 2021-11-26 00:01

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('addreses', models.CharField(max_length=120, null=True, verbose_name='العنوان')),
                ('mobile', models.CharField(max_length=50, null='true', verbose_name='رقم التلفون')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاظافة')),
                ('active', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'وكيل',
                'verbose_name_plural': 'الوكلاء',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='رقم الفرع')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفرع')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('active', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('description', models.TextField(blank=True, verbose_name='ملاحظة')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('job', models.CharField(blank=True, max_length=250, null=True, verbose_name='المهنة')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='الموبايل')),
                ('passport_No', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الجواز')),
                ('bond_No', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم السند')),
                ('hospital', models.CharField(blank=True, max_length=255, null=True, verbose_name='المستشفى')),
                ('examination_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ الفحص')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاظافة')),
                ('active', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelAgentMain.agent', verbose_name='الوكيل')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelAgentMain.branch', verbose_name='الفرع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='Customer_Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نوع المرفق')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'انواع المرفقات',
            },
        ),
        migrations.CreateModel(
            name='Customer_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نوع الحالة')),
            ],
            options={
                'verbose_name': 'الحالة',
                'verbose_name_plural': 'انواع الحالة',
            },
        ),
        migrations.CreateModel(
            name='Visas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_visa', models.CharField(max_length=100, unique=True, verbose_name='رقم التأشيره')),
                ('record_No', models.CharField(max_length=100, verbose_name='رقم السجل')),
                ('authorization_No', models.CharField(blank=True, max_length=100, verbose_name='رقم التفويض')),
                ('visa_type', models.CharField(choices=[('work', 'عمل'), ('omrah', 'عمره'), ('haj', 'حج'), ('vist', 'زياره')], default='work', max_length=100, verbose_name='نوع التأشيره')),
                ('count_visa', models.IntegerField(verbose_name='عدد التأشيرات')),
                ('company', models.CharField(max_length=255, verbose_name='الشركة')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الاظافة')),
                ('active', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visaEdit', to=settings.AUTH_USER_MODEL, verbose_name='اخر تعديل ب:')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تأشيره',
                'verbose_name_plural': 'التأشيرات',
            },
        ),
        migrations.CreateModel(
            name='Customer_Status_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاظافة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelAgentMain.customer', verbose_name='المستخدم')),
                ('customer_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelAgentMain.customer_status', verbose_name='جالة الجواز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'متابعة التأشيره',
                'verbose_name_plural': 'تتبع التأشيرات',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='visa_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelAgentMain.visas', verbose_name='رقم التأشيره'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vist_attachments',
            field=models.ManyToManyField(blank=True, to='travelAgentMain.Customer_Attachments', verbose_name='المرفقات'),
        ),
    ]
