# Generated by Django 3.2.9 on 2021-11-26 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='المبلغ المتفق'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_status',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ الحالة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='moaasher_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التأشير'),
        ),
        migrations.AddField(
            model_name='customer',
            name='murahal_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الترحيل'),
        ),
        migrations.AddField(
            model_name='customer',
            name='receveFromkuafel_date',
            field=models.DateField(blank=True, help_text='تارخ الاستلام من قوافل', null=True, verbose_name='استلام قوافل'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sendTokuafel_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ تسليم قوافل'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('process', 'تحت الاجراء'), ('murahal', 'مرحل'), ('sendTokuafel', 'تسليم قوافل'), ('moaasher', 'مؤشر'), ('receveFromkuafel', 'تم الاستلام من قوافل')], default='process', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
