# Generated by Django 3.2.9 on 2021-11-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0002_auto_20211126_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visas',
            name='authorization_No',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='رقم التفويض'),
        ),
    ]
