# Generated by Django 3.2.9 on 2021-11-26 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelAgentMain', '0003_alter_visas_authorization_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='المبلغ المتفق'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الاظافة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
