# Generated by Django 3.2.9 on 2021-11-26 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelAgentMain', '0004_auto_20211126_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاظافة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='examination_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ الفحص'),
        ),
    ]
