# Generated by Django 3.2.9 on 2021-11-26 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0005_auto_20211126_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='examination_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ الفحص'),
        ),
    ]
