# Generated by Django 3.2.9 on 2021-11-26 18:28

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelAgentMain', '0008_auto_20211126_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=crum.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerEdit', to=settings.AUTH_USER_MODEL, verbose_name='اخر تعديل بواسطة:'),
        ),
    ]
