# Generated by Django 3.2.9 on 2021-11-26 21:15

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelAgentMain', '0009_customer_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelAgentMain.agent', verbose_name='الوكيل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelAgentMain.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CustomerEdit', to=settings.AUTH_USER_MODEL, verbose_name='اخر تعديل بواسطة:'),
        ),
        migrations.AlterField(
            model_name='visas',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=crum.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visaEdit', to=settings.AUTH_USER_MODEL, verbose_name='اخر تعديل ب:'),
        ),
    ]
