# Generated by Django 3.2.9 on 2021-12-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0010_auto_20211127_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='baptisms',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التعميدات'),
        ),
        migrations.AddField(
            model_name='customer',
            name='health_insurance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='التأمين الصحيس'),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_No',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الطلب'),
        ),
    ]
