# Generated by Django 3.2.9 on 2022-02-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0011_auto_20211226_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Remaining_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='المبلغ المتبقي'),
        ),
    ]
