# Generated by Django 3.2.9 on 2022-04-21 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelAgentMain', '0012_customer_remaining_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500, verbose_name='النص')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاظافة')),
                ('Status', models.BooleanField(default=False, verbose_name='المستخدم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اضافة خبر',
                'verbose_name_plural': 'الاخبار',
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('job', models.CharField(blank=True, max_length=250, null=True, verbose_name='المهنة')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='الموبايل')),
                ('passport_No', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الجواز')),
                ('bond_No', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم السجل')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاظافة')),
                ('visa_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelAgentMain.visas', verbose_name='رقم التأشيره')),
            ],
            options={
                'verbose_name': 'تفويض',
                'verbose_name_plural': 'التفويضات',
            },
        ),
    ]
