# Generated by Django 3.2.9 on 2022-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0013_mandate_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='visa_No',
            field=models.CharField(max_length=50, verbose_name='رقم التأشيره'),
        ),
    ]
