# Generated by Django 3.2.9 on 2022-05-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0014_alter_mandate_visa_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='murahal_system',
            field=models.BooleanField(default=False, help_text='تمت الصادقة من قبل الادارة', verbose_name='مرحل'),
        ),
    ]
