# Generated by Django 3.2.9 on 2022-05-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0017_alter_customer_murahal_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='note_murahal_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة الادارة'),
        ),
    ]
