# Generated by Django 3.2.9 on 2022-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0018_customer_note_murahal_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passport_No',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='رقم الجواز'),
        ),
    ]
