# Generated by Django 3.2.9 on 2022-07-04 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0019_alter_customer_passport_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image_agreement',
            field=models.ImageField(blank=True, default='image_id.png', null=True, upload_to='image_id/', verbose_name='صورة الاتفاقية'),
        ),
        migrations.AddField(
            model_name='agent',
            name='image_id',
            field=models.ImageField(blank=True, default='image_agreement.jpg', null=True, upload_to='image_agreements/', verbose_name='صورة الهوية'),
        ),
        migrations.CreateModel(
            name='PrintSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_Name', models.CharField(max_length=20, verbose_name='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelAgentMain.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'بروفايل المستخدم',
                'verbose_name_plural': 'بروفايل المستخدمين',
            },
        ),
    ]
