# Generated by Django 4.2.1 on 2023-05-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAgentMain', '0020_auto_20220704_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image_agreement',
            field=models.ImageField(blank=True, null=True, upload_to='image_id/', verbose_name='صورة الاتفاقية'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='image_id',
            field=models.ImageField(blank=True, null=True, upload_to='image_agreements/', verbose_name='صورة الهوية'),
        ),
    ]
